# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'DysonWars' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DysonWars

  pod 'Moscapsule', :git => 'https://github.com/flightonary/Moscapsule.git'
  pod 'OpenSSL-Universal', '~> 1.0.1.18'
  pod 'OpenCV'

end
